# Generated by Django 6.1.1 on 2026-10-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_pet_user_alter_appointment_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='veterinarian',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
